"""
image_export.py — Convert document PDF bytes to a downloadable PNG image.

Strategy:
  1. Try pdf2image (poppler-based) if available – best quality.
  2. Fallback: Re-render the document directly as an image using Pillow + FPDF
     by drawing a styled receipt card (no poppler dependency required).
"""

import io
from PIL import Image, ImageDraw, ImageFont


def _draw_text(draw: ImageDraw.ImageDraw, x: int, y: int, text: str, font, fill=(23, 26, 29)):
    draw.text((x, y), text, font=font, fill=fill)
    return y


def _try_load_font(size: int):
    """Try to load a system monospace/sans font, fall back to default."""
    candidates = [
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
        "/usr/share/fonts/truetype/freefont/FreeSansBold.ttf",
        "/usr/share/fonts/truetype/ubuntu/Ubuntu-B.ttf",
    ]
    for path in candidates:
        try:
            return ImageFont.truetype(path, size)
        except Exception:
            continue
    return ImageFont.load_default()


def _try_load_mono_font(size: int):
    candidates = [
        "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
        "/usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf",
        "/usr/share/fonts/truetype/freefont/FreeMono.ttf",
        "/usr/share/fonts/truetype/ubuntu/UbuntuMono-R.ttf",
    ]
    for path in candidates:
        try:
            return ImageFont.truetype(path, size)
        except Exception:
            continue
    return ImageFont.load_default()


def pdf_bytes_to_png(pdf_bytes: bytes, doc_title: str, doc_no: str, rows: list[tuple[str, str]]) -> bytes:
    """
    Render a document image from field pairs.

    Args:
        pdf_bytes: The raw PDF bytes (kept for potential future use with poppler).
        doc_title: e.g. "PURCHASE ORDER"
        doc_no: e.g. "PO-0001"
        rows: list of (label, value) tuples to render as a table

    Returns:
        PNG image as bytes.
    """
    # --- Try pdf2image first (best quality) ---
    try:
        from pdf2image import convert_from_bytes
        images = convert_from_bytes(pdf_bytes, dpi=150)
        if images:
            buf = io.BytesIO()
            # Stitch pages vertically if multi-page
            if len(images) == 1:
                images[0].save(buf, format="PNG")
            else:
                widths, heights = zip(*(i.size for i in images))
                total_height = sum(heights)
                combined = Image.new("RGB", (max(widths), total_height), color=(255, 255, 255))
                y_offset = 0
                for img in images:
                    combined.paste(img, (0, y_offset))
                    y_offset += img.height
                combined.save(buf, format="PNG")
            buf.seek(0)
            return buf.read()
    except Exception:
        pass  # Fall through to Pillow-native renderer

    # --- Pillow-native renderer (no poppler needed) ---
    WIDTH = 900
    PADDING = 48
    ROW_HEIGHT = 38
    HEADER_HEIGHT = 130
    FOOTER_HEIGHT = 50

    total_height = HEADER_HEIGHT + (ROW_HEIGHT * len(rows)) + FOOTER_HEIGHT + PADDING * 2

    # Background
    img = Image.new("RGB", (WIDTH, total_height), color=(239, 241, 234))  # paper tint
    draw = ImageDraw.Draw(img)

    # Fonts
    font_title = _try_load_font(22)
    font_doc_no = _try_load_mono_font(16)
    font_label = _try_load_font(13)
    font_value = _try_load_mono_font(13)
    font_brand = _try_load_font(14)
    font_footer = _try_load_font(10)

    # Header bar
    draw.rectangle([(0, 0), (WIDTH, 60)], fill=(23, 26, 29))
    draw.text((PADDING, 16), "HealthPilot Ops", font=font_brand, fill=(255, 255, 255))

    # Title & doc number
    draw.text((PADDING, 72), doc_title, font=font_title, fill=(166, 100, 42))
    draw.text((PADDING, 100), f"Document No: {doc_no}", font=font_doc_no, fill=(23, 26, 29))

    # Divider
    draw.line([(PADDING, HEADER_HEIGHT - 10), (WIDTH - PADDING, HEADER_HEIGHT - 10)], fill=(200, 200, 200), width=1)

    # Table rows
    label_w = 220
    value_x = PADDING + label_w + 12
    y = HEADER_HEIGHT + PADDING // 2

    for i, (label, value) in enumerate(rows):
        row_bg = (255, 255, 255) if i % 2 == 0 else (245, 246, 242)
        draw.rectangle([(PADDING, y), (WIDTH - PADDING, y + ROW_HEIGHT - 4)], fill=row_bg, outline=(220, 220, 220))
        # Label
        draw.text((PADDING + 10, y + 10), label, font=font_label, fill=(80, 80, 80))
        # Value
        draw.text((value_x, y + 10), str(value), font=font_value, fill=(23, 26, 29))
        y += ROW_HEIGHT

    # Footer
    footer_y = total_height - FOOTER_HEIGHT + 10
    draw.line([(PADDING, footer_y - 5), (WIDTH - PADDING, footer_y - 5)], fill=(200, 200, 200), width=1)
    draw.text((PADDING, footer_y), f"Generated by HealthPilot.ai  |  {doc_no}", font=font_footer, fill=(138, 143, 135))

    buf = io.BytesIO()
    img.save(buf, format="PNG", optimize=True)
    buf.seek(0)
    return buf.read()
